### ISSUE TITLE
Fix save comment issue

### ISSUE THREAD

**Issue by maruf9270** [Masitbd/mas-hms-frontend#31]
The comment is working fine. But the issue is when the saved comment is selected from the dropdown the comment is not showing in the tiptap editor.
Possible fix: The editor may need to be reconfigured to fix this issue

**Note: All comment related code is in the comment component** 
Front end : **generate-report-patameter-based** 
server: **new-pdf-generator**
api gateway: **main**
![dev](https://github.com/user-attachments/assets/c0c97d40-70ac-46ba-b685-ac2099882783)
![dev1](https://github.com/user-attachments/assets/4c880675-725f-422a-be1d-74645015dcf7)

**Comment by YeasinHowladerEmon** [comment]
solve this issue
